Add basic header-based routing
tikon93/fastapi-header-versioning pull request #1
Opened 2023-09-18 19:09 UTC by tikon93

2023-09-18 19:50 UTC, Ovsyanka83 requested changes
Nice job! This is **a lot** of nice work.

2023-09-18 19:50 UTC, Ovsyanka83 commented on examples.py
> +from fastapi_hbr import HeaderBasedRoutingFastApi, HeaderVersionedAPIRouter, CustomHeaderVersionMiddleware
I am not a huge fan of abbreviations. Maybe just rename it to fastapi-header-versioning and do `fastapi_header_versioning` package?

2023-09-18 19:50 UTC, Ovsyanka83 commented on examples.py
> +GREETINGS_LATEST = "Hello, can you hear me?"
I feel like there's no need to have them as global constants in examples as it increases example size without making it more clear. Wdyt?

2023-09-18 19:50 UTC, Ovsyanka83 commented on examples.py
> +app.include_router(router)
I believe that this middleware should be a part of the app. I.e. The app should add it automatically. Sounds like a nicer interface.

2023-09-18 19:50 UTC, Ovsyanka83 commented on examples.py
> +app = HeaderBasedRoutingFastApi(title="Versioned app")
Let's name it `HeaderBasedRoutingFastAPI` instead. Let's use the capital `API` everywhere because otherwise it's inconsistent with FastAPI

2023-09-18 19:50 UTC, Ovsyanka83 commented on fastapi_hbr/fastapi.py
> +        self, app: ASGI3Application, version_header: str,
Why ASGI3? I am not against it but that's the first time I see these type hints.

2023-09-18 19:50 UTC, Ovsyanka83 commented on fastapi_hbr/fastapi.py
> +from typing import Any, Callable, Dict, List, Optional, Sequence, Type, Union
It's a good idea to use these! This will allow you and your library to support older pythons which sounds like a killer feature compared to universi which isn't capable of supporting anything pre-3.10. I'd suggest >=3.8 as 3.7 was deprecated, I think.

2023-09-18 19:50 UTC, Ovsyanka83 commented on fastapi_hbr/routing.py
> +    await response(scope, receive, send)
Will we be able to support version cascades tho?

Like the user sent us version 2023 but we only have 2022

2023-09-18 19:50 UTC, Ovsyanka83 commented on fastapi_hbr/routing.py
> +            return Match.FULL, child_scope
Starlette matches keep confusing the hell out of me. I hope I'll be able to comprehend them some day. No problem with your code though.

2023-09-18 19:50 UTC, Ovsyanka83 commented on fastapi_hbr/routing.py
> +    ) -> None:
Considering that this is a public interface, we'll need to expand all args kwargs or use typing tricks (same goes for all other args and kwargs). Otherwise our users won't be able to use this lib comfortably with type checking. Either way let's just add todos and handle it later.
```suggestion
    # TODO: Make sure we show the entire interface of the function to the users later
    def include_router(
            self,
            router: "APIRouter",
            *args: Any,
            **kwargs: Any
    ) -> None:
```

2023-09-18 19:50 UTC, Ovsyanka83 commented on fastapi_hbr/routing.py
> +        if requested_version is not None and requested_version not in self.registered_versions:
Really nice!

2023-09-19 06:18 UTC, tikon93 commented on fastapi_hbr/routing.py
> +    ) -> None:
I guess copypasting the whole interface of original function works?
And same for other overrided methods (eg couple of __init__s)?

2023-09-19 06:18 UTC, tikon93 commented on fastapi_hbr/routing.py
> +    await response(scope, receive, send)
it's a specific route. routing to older, but still suitable version occurs at router level, check https://github.com/tikon93/fastapi-header-versioning/pull/1/files#diff-ecf8c902bf61887531d37b3ba311dc01798c8dc8613f7e210e164b3ec8423d1dR105

2023-09-19 06:18 UTC, tikon93 commented on fastapi_hbr/fastapi.py
> +        self, app: ASGI3Application, version_header: str,
actually it was a copypaste. guess we can reduce it to FastAPI to make our life easier

2023-09-19 06:18 UTC, tikon93 commented on fastapi_hbr/fastapi.py
> +from typing import Any, Callable, Dict, List, Optional, Sequence, Type, Union
well, if to be conscious about it - I'll need to use it all over the lib. TBH it's taken from https://github.com/tiangolo/fastapi/issues/3910#issuecomment-1024132161, but it's a nice idea to make it compatible with older python versions

2023-09-19 06:18 UTC, tikon93 commented on examples.py
> +app.include_router(router)
also got the same idea, probably we'll just need `version_header` arg at app-level

2023-09-19 06:18 UTC, tikon93 commented on examples.py
> +GREETINGS_LATEST = "Hello, can you hear me?"
I'll change all the examples, it's just a copypaste from https://github.com/tiangolo/fastapi/issues/3910#issuecomment-1024132161 for your evaluation

2023-09-19 06:30 UTC, Ovsyanka83 commented on fastapi_hbr/routing.py
> +    ) -> None:
Yes. However, there's also the alternative approach which could be preferable: using typing to say that your interface is the same as the interface in the original while having args and kwargs yourself. It makes your code uglier but will evolve better once fastapi adds anything. 

I guess my rule of thumb is: use typing fuckery if arg types and names are the same and use full copying if anything's different.

2023-09-25 18:17 UTC, merged